export const ingredientNameList: Record<number, string | undefined> = {
	// Fishes
	1: 'merou_lujidane',
	2: 'poisson_vengeur',
	3: 'an_guili_guilille',
	4: 'globulos',
	5: 'super_poisson',
	// Hunting
	6: 'touffe_de_fourrure',
	7: 'griffes_acerees',
	8: 'corne_en_chocolat',
	9: 'oeil_visqueux',
	10: 'langue_monstrueuse',
	11: 'dent_de_dorogon',
	12: 'roche_radio_active',
	// Energies
	13: 'energie_foudre',
	14: 'energie_air',
	15: 'energie_eau',
	16: 'energie_feu',
	17: 'energie_bois',
	// Artifacts
	18: 'silex_taille',
	19: 'fragment_de_texte_ancien',
	20: 'vieil_anneau_precieux',
	21: 'calice_cisele',
	22: 'collier_karat',
	23: 'broche_en_parfait_etat',
	24: 'superbe_couronne_royale',
	25: 'bras_mecanique',
	// Plants
	26: 'feuilles_de_pelinae',
	27: 'bolet_phalisk_blanc',
	28: 'orchidee_fantasque',
	29: 'racine_de_figonicia',
	30: 'sadiquae_mordicus',
	31: 'flaureole',
	32: 'spore_etheral',
	33: 'pousse_sombre',
	// Special
	34: 'graine_de_devoreuse'
};
