/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, '__esModule', { value: true });

const {
	PrismaClientKnownRequestError,
	PrismaClientUnknownRequestError,
	PrismaClientRustPanicError,
	PrismaClientInitializationError,
	PrismaClientValidationError,
	getPrismaClient,
	sqltag,
	empty,
	join,
	raw,
	skip,
	Decimal,
	Debug,
	DbNull,
	JsonNull,
	AnyNull,
	NullTypes,
	makeStrictEnum,
	Extensions,
	warnOnce,
	defineDmmfProperty,
	Public,
	getRuntime,
	createParam
} = require('./runtime/wasm-compiler-edge.js');

const Prisma = {};

exports.Prisma = Prisma;
exports.$Enums = {};

/**
 * Prisma Client JS version: 7.0.0
 * Query Engine version: 0c19ccc313cf9911a90d99d2ac2eb0280c76c513
 */
Prisma.prismaVersion = {
	client: '7.0.0',
	engine: '0c19ccc313cf9911a90d99d2ac2eb0280c76c513'
};

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError;
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError;
Prisma.PrismaClientInitializationError = PrismaClientInitializationError;
Prisma.PrismaClientValidationError = PrismaClientValidationError;
Prisma.Decimal = Decimal;

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag;
Prisma.empty = empty;
Prisma.join = join;
Prisma.raw = raw;
Prisma.validator = Public.validator;

/**
 * Extensions
 */
Prisma.getExtensionContext = Extensions.getExtensionContext;
Prisma.defineExtension = Extensions.defineExtension;

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull;
Prisma.JsonNull = JsonNull;
Prisma.AnyNull = AnyNull;

Prisma.NullTypes = NullTypes;

/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
	ReadUncommitted: 'ReadUncommitted',
	ReadCommitted: 'ReadCommitted',
	RepeatableRead: 'RepeatableRead',
	Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
	id: 'id',
	name: 'name',
	password: 'password',
	createdDate: 'createdDate'
};

exports.Prisma.RelationLoadStrategy = {
	query: 'query',
	join: 'join'
};

exports.Prisma.SortOrder = {
	asc: 'asc',
	desc: 'desc'
};

exports.Prisma.QueryMode = {
	default: 'default',
	insensitive: 'insensitive'
};

exports.Prisma.ModelName = {
	User: 'User'
};
/**
 * Create the Client
 */
const config = {
	previewFeatures: ['nativeDistinct', 'relationJoins'],
	clientVersion: '7.0.0',
	engineVersion: '0c19ccc313cf9911a90d99d2ac2eb0280c76c513',
	activeProvider: 'postgresql',
	inlineSchema:
		'generator client {\n  provider        = "prisma-client-js"\n  output          = "../../prisma"\n  previewFeatures = ["nativeDistinct", "relationJoins"]\n  binaryTargets   = ["native", "debian-openssl-3.0.x", "debian-openssl-1.1.x"]\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel User {\n  id          String   @id @default(uuid())\n  name        String   @unique\n  password    String\n  createdDate DateTime @default(now())\n}\n'
};

config.runtimeDataModel = JSON.parse(
	'{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdDate","kind":"scalar","type":"DateTime"}],"dbName":null}},"enums":{},"types":{}}'
);
defineDmmfProperty(exports.Prisma, config.runtimeDataModel);
config.compilerWasm = {
	getRuntime: async () => require('./query_compiler_bg.js'),
	getQueryCompilerWasmModule: async () => {
		const loader = (await import('#wasm-compiler-loader')).default;
		const compiler = (await loader).default;
		return compiler;
	}
};
if (
	(typeof globalThis !== 'undefined' && globalThis['DEBUG']) ||
	(typeof process !== 'undefined' && process.env && process.env.DEBUG) ||
	undefined
) {
	Debug.enable(
		(typeof globalThis !== 'undefined' && globalThis['DEBUG']) ||
			(typeof process !== 'undefined' && process.env && process.env.DEBUG) ||
			undefined
	);
}

const PrismaClient = getPrismaClient(config);
exports.PrismaClient = PrismaClient;
Object.assign(exports, Prisma);
