
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.4.2
 * Query Engine version: 94a226be1cf2967af2541cca5529f0f7ba866919
 */
Prisma.prismaVersion = {
  client: "7.4.2",
  engine: "94a226be1cf2967af2541cca5529f0f7ba866919"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.DinozScalarFieldEnum = {
  id: 'id',
  name: 'name',
  canRename: 'canRename',
  raceId: 'raceId',
  display: 'display',
  level: 'level',
  life: 'life',
  maxLife: 'maxLife',
  experience: 'experience',
  nbrUpFire: 'nbrUpFire',
  nbrUpWood: 'nbrUpWood',
  nbrUpWater: 'nbrUpWater',
  nbrUpLightning: 'nbrUpLightning',
  nbrUpAir: 'nbrUpAir',
  nextUpElementId: 'nextUpElementId',
  nextUpAltElementId: 'nextUpAltElementId',
  placeId: 'placeId',
  remaining: 'remaining',
  order: 'order',
  createdDate: 'createdDate',
  updatedDate: 'updatedDate',
  seed: 'seed',
  state: 'state',
  stateTimer: 'stateTimer',
  fight: 'fight',
  gather: 'gather',
  leaderId: 'leaderId',
  userId: 'userId'
};

exports.Prisma.RelationLoadStrategy = {
  query: 'query',
  join: 'join'
};

exports.Prisma.DinozCatchScalarFieldEnum = {
  id: 'id',
  dinozId: 'dinozId',
  hp: 'hp',
  monsterId: 'monsterId'
};

exports.Prisma.DinozItemsScalarFieldEnum = {
  id: 'id',
  itemId: 'itemId',
  dinozId: 'dinozId'
};

exports.Prisma.DinozSkillsScalarFieldEnum = {
  id: 'id',
  skillId: 'skillId',
  state: 'state',
  dinozId: 'dinozId'
};

exports.Prisma.DinozSkillsUnlockableScalarFieldEnum = {
  id: 'id',
  skillId: 'skillId',
  dinozId: 'dinozId'
};

exports.Prisma.DinozStatusScalarFieldEnum = {
  id: 'id',
  statusId: 'statusId',
  dinozId: 'dinozId'
};

exports.Prisma.JobDefinitionScalarFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  type: 'type',
  enabled: 'enabled',
  timezone: 'timezone',
  dailyHour: 'dailyHour',
  dailyMinute: 'dailyMinute',
  intervalMs: 'intervalMs',
  status: 'status',
  lastRunAt: 'lastRunAt',
  nextRunAt: 'nextRunAt',
  lastError: 'lastError',
  lockedAt: 'lockedAt',
  lockedBy: 'lockedBy',
  lockTimeoutS: 'lockTimeoutS',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobRunScalarFieldEnum = {
  id: 'id',
  jobId: 'jobId',
  startedAt: 'startedAt',
  endedAt: 'endedAt',
  success: 'success',
  error: 'error',
  triggeredBy: 'triggeredBy'
};

exports.Prisma.RankingScalarFieldEnum = {
  id: 'id',
  dinozCount: 'dinozCount',
  points: 'points',
  average: 'average',
  completion: 'completion',
  dojo: 'dojo',
  userId: 'userId'
};

exports.Prisma.SecretScalarFieldEnum = {
  key: 'key',
  value: 'value'
};

exports.Prisma.SignupDeviceMonthCounterScalarFieldEnum = {
  id: 'id',
  monthKey: 'monthKey',
  deviceToken: 'deviceToken',
  count: 'count',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SignupIpMonthCounterScalarFieldEnum = {
  id: 'id',
  monthKey: 'monthKey',
  ipToken: 'ipToken',
  count: 'count',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  password: 'password',
  role: 'role',
  createdDate: 'createdDate',
  updatedAt: 'updatedAt',
  lastLogin: 'lastLogin',
  leader: 'leader',
  engineer: 'engineer',
  cooker: 'cooker',
  shopKeeper: 'shopKeeper',
  merchant: 'merchant',
  priest: 'priest',
  teacher: 'teacher',
  matelasseur: 'matelasseur',
  messie: 'messie'
};

exports.Prisma.UserDinozShopScalarFieldEnum = {
  id: 'id',
  raceId: 'raceId',
  display: 'display',
  userId: 'userId'
};

exports.Prisma.UserGatherScalarFieldEnum = {
  id: 'id',
  place: 'place',
  type: 'type',
  grid: 'grid',
  userId: 'userId'
};

exports.Prisma.UserIngredientsScalarFieldEnum = {
  id: 'id',
  ingredientId: 'ingredientId',
  quantity: 'quantity',
  userId: 'userId'
};

exports.Prisma.UserItemsScalarFieldEnum = {
  id: 'id',
  itemId: 'itemId',
  quantity: 'quantity',
  userId: 'userId'
};

exports.Prisma.UserProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  avatar: 'avatar',
  avatarType: 'avatarType',
  language: 'language',
  gender: 'gender',
  age: 'age',
  description: 'description'
};

exports.Prisma.UserRewardsScalarFieldEnum = {
  id: 'id',
  rewardId: 'rewardId',
  userId: 'userId'
};

exports.Prisma.UserTrackingScalarFieldEnum = {
  id: 'id',
  stat: 'stat',
  quantity: 'quantity',
  userId: 'userId'
};

exports.Prisma.UserWalletScalarFieldEnum = {
  id: 'id',
  type: 'type',
  amount: 'amount',
  userId: 'userId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.DinozState = exports.$Enums.DinozState = {
  frozen: 'frozen',
  sacrificed: 'sacrificed',
  selling: 'selling',
  superdom: 'superdom',
  resting: 'resting',
  unfreezing: 'unfreezing'
};

exports.JobType = exports.$Enums.JobType = {
  DAILY_AT: 'DAILY_AT',
  INTERVAL: 'INTERVAL'
};

exports.JobStatus = exports.$Enums.JobStatus = {
  IDLE: 'IDLE',
  RUNNING: 'RUNNING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED'
};

exports.Role = exports.$Enums.Role = {
  PLAYER: 'PLAYER',
  MODERATOR: 'MODERATOR',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN'
};

exports.Language = exports.$Enums.Language = {
  FR: 'FR',
  EN: 'EN',
  ES: 'ES',
  DE: 'DE'
};

exports.Gender = exports.$Enums.Gender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER'
};

exports.MoneyType = exports.$Enums.MoneyType = {
  GOLD: 'GOLD',
  TREASURE_TICKET: 'TREASURE_TICKET'
};

exports.Prisma.ModelName = {
  Dinoz: 'Dinoz',
  DinozCatch: 'DinozCatch',
  DinozItems: 'DinozItems',
  DinozSkills: 'DinozSkills',
  DinozSkillsUnlockable: 'DinozSkillsUnlockable',
  DinozStatus: 'DinozStatus',
  JobDefinition: 'JobDefinition',
  JobRun: 'JobRun',
  Ranking: 'Ranking',
  Secret: 'Secret',
  SignupDeviceMonthCounter: 'SignupDeviceMonthCounter',
  SignupIpMonthCounter: 'SignupIpMonthCounter',
  User: 'User',
  UserDinozShop: 'UserDinozShop',
  UserGather: 'UserGather',
  UserIngredients: 'UserIngredients',
  UserItems: 'UserItems',
  UserProfile: 'UserProfile',
  UserRewards: 'UserRewards',
  UserTracking: 'UserTracking',
  UserWallet: 'UserWallet'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
