import { Ingredient } from '../ingredients/ingredientList.js';
import { DayEnum } from './DayType.js';
import { Comparator, ConditionEnum, Operator } from './Parser.js';
import { PlaceEnum } from './PlaceEnum.js';

export type Condition = {
	[Operator.AND]?: [Condition, Condition, ...Condition[]];
	[Operator.OR]?: [Condition, Condition, ...Condition[]];
	[Operator.NOT]?: Condition;
	[ConditionEnum.MINLEVEL]?: number;
	[ConditionEnum.MAXLEVEL]?: number;
	//[ConditionEnum.FINISHED_MISSION]?: MissionID;
	[ConditionEnum.SKILL]?: number;
	[ConditionEnum.POSSESS_OBJECT]?: number;
	[ConditionEnum.COLLEC]?: number;
	[ConditionEnum.STATUS]?: number;
	[ConditionEnum.RANDOM]?: number;
	[ConditionEnum.DINOZ_LIFE]?: [Comparator, number];
	//[ConditionEnum.SCENARIO]?: [Scenario, number, '+' | '-' | '='];
	[ConditionEnum.CURRENT_MISSION]?: number;
	[ConditionEnum.POSSESS_INGREDIENT]?: [Ingredient, Comparator, number];
	[ConditionEnum.ACTIVE]?: boolean;
	[ConditionEnum.PLAYER_EPIC]?: number;
	[ConditionEnum.HOUR]?: number;
	[ConditionEnum.TAG]?: string;
	[ConditionEnum.GVAR]?: string;
	[ConditionEnum.EVENT]?: string;
	[ConditionEnum.CLANACT]?: string;
	[ConditionEnum.SWAIT]?: string;
	[ConditionEnum.RACE]?: string;
	[ConditionEnum.EQUIP]?: number;
	[ConditionEnum.TIME]?: number;
	[ConditionEnum.UTIME]?: string;
	[ConditionEnum.GOTO]?: string;
	[ConditionEnum.TALKTO]?: string;
	[ConditionEnum.FINISH_MISSION]?: string;
	[ConditionEnum.KILL]?: string;
	[ConditionEnum.DO]?: string;
	[ConditionEnum.HIDE_PLACE]?: string;
	[ConditionEnum.PLACE_IS]?: PlaceEnum;
	[ConditionEnum.OVERWRITE]?: string;
	[ConditionEnum.LAUNCH_FIGHT]?: string;
	[ConditionEnum.DAY]?: DayEnum;
	[ConditionEnum.CURRENT_STEP]?: number;
	[ConditionEnum.DINOZ_COUNT]?: [Comparator, number];
	[ConditionEnum.PLAYER_POINT]?: [Comparator, number];
};
