import { levelList } from '../models/dinoz/dinozLevel.js';
import { DinozForMaxXp } from '../models/dinoz/dinozXP.js';
import { raceList } from '../models/dinoz/raceList.js';
import { DinozStatusId } from '../models/dinoz/statusList.js';
import { placeList } from '../models/place/placeList.js';
import { ExpectedError } from '../models/utils/expectedError.js';

export const getRace = (raceId: number) => {
	const race = Object.values(raceList).find(r => r.raceId === raceId);

	if (!race) {
		throw new ExpectedError(`Race ${raceId} doesn't exist.`);
	}

	return race;
};

export const getMaxXp = (dinoz: DinozForMaxXp): number => {
	const level = levelList.find(l => l.id === dinoz.level);
	if (!level) throw new Error(`Level ${dinoz.level} doesn't exist.`);

	if (dinoz.status.some(s => s.statusId !== DinozStatusId.BROKEN_LIMIT_3) && dinoz.level === 70) return 0;
	if (dinoz.status.some(s => s.statusId !== DinozStatusId.BROKEN_LIMIT_2) && dinoz.level === 60) return 0;
	if (dinoz.status.some(s => s.statusId !== DinozStatusId.BROKEN_LIMIT_1) && dinoz.level === 50) return 0;

	return level.experience;
};

export type HasPlaceId = { placeId: number };

export const actualPlace = (dinoz: HasPlaceId) => {
	const place = Object.values(placeList).find(p => p.placeId === dinoz.placeId);

	if (!place) {
		throw new Error(`Place ${dinoz.placeId} doesn't exist.`);
	}

	return place;
};

/**
 * @summary Calculate the XP before bonus for a PvP fight
 * @param opponentLevel Level of the opponent
 * @param dinozLevel Level of the Dinoz that fought the opponent
 * @returns The experience the Dinoz is entitled to receive before bonuses
 */
export const calculatePvPxp = (opponentLevel: number, dinozLevel: number) => {
	const BASE_PVP_XP = 50;
	const XP_BASE = 1.2;
	const XP_ADD = 0.8;
	const PVP_COEF = 2.5;

	// Factor based on the level difference
	const levelDiff = (opponentLevel - dinozLevel) / opponentLevel;
	// XP result solely base on the level difference
	const xpFactor = XP_BASE + XP_ADD * levelDiff;
	let xp;
	if (xpFactor < 1) {
		// If the experience  factor based on the level difference too low (i.e Dinoz level is higher than its opponents), then default to a formula based on the opponents level.
		xp = PVP_COEF * opponentLevel;
	} else {
		// Else the opponent's level is equal or higher than the Dinoz, then apply the PVP coef and opponent level to the xp factor based on the level difference.
		xp = xpFactor * PVP_COEF * opponentLevel;
	}

	// Set the minimum to the BASE PVP
	return Math.max(xp, BASE_PVP_XP);
};

/**
 * @summary Calculate the XP before bonus for a PvE fight
 * @param totalMonsterXp Total xp generated by the monsters
 * @param dinozLevel Level of the Dinoz
 * @param maxLevel Maximum achievable level
 * @param initialMaxLevel First max level limit in the game
 * @returns The experience the Dinoz is entitled to receive before bonuses
 */
export const calculatePvExp = (
	totalMonsterXp: number,
	dinozLevel: number,
	maxLevel: number,
	initialMaxLevel: number
) => {
	const XP_BASE = 1.2;
	const XP_ADD = 0.8;
	// Minimum factor applie to the total monster xp
	const MINIMUM_XP_FACTOR = 1.0;
	// Multiplicator constant to increase/decrease result as necessary
	const XP_MULTIPLICATOR = 1.0;

	// Factor based on the level difference
	const levelDiff = (maxLevel - dinozLevel) / maxLevel;

	// XP factor to apply to the total
	let xpFactor = Math.max(XP_BASE + XP_ADD * levelDiff, MINIMUM_XP_FACTOR);

	// Apply new factor when max level limit increases
	if (maxLevel / initialMaxLevel > xpFactor) xpFactor = maxLevel / initialMaxLevel;

	return Math.round(totalMonsterXp * xpFactor * XP_MULTIPLICATOR);
};
