-- AlterTable
ALTER TABLE "Dinoz" ALTER COLUMN "createdDate" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updatedDate" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "SignupDeviceMonthCounter" ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "SignupIpMonthCounter" ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "createdDate" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "lastLogin" SET DATA TYPE TIMESTAMPTZ(3);
