import { DinozStatusId } from './statusList.js';

export const dinozStatusIdByKey: Partial<Record<string, DinozStatusId>> = {
	bouee: DinozStatusId.BUOY,
	matesc: DinozStatusId.CLIMBING_GEAR,
	lantrn: DinozStatusId.LANTERN,
	pelle: DinozStatusId.SHOVEL,
	pelle2: DinozStatusId.ENHANCED_SHOVEL,
	brkpel: DinozStatusId.BROKEN_SHOVEL,
	brkpe2: DinozStatusId.BROKEN_ENHANCED_SHOVEL,
	marais: DinozStatusId.SWAMP_MUD,
	wpure: DinozStatusId.PURE_WATER,
	basalt: DinozStatusId.BASALT_SHARD,
	gant: DinozStatusId.ZORS_GLOVE,
	zenbro: DinozStatusId.ZENBRO,
	nenuph: DinozStatusId.NENUPHAR_LEAF,
	chutes: DinozStatusId.CHUTES,
	jvbz: DinozStatusId.JVBZ,
	qwood: DinozStatusId.QWOOD,
	qwhy: DinozStatusId.QWHY,
	qtame: DinozStatusId.QTAME,
	dian: DinozStatusId.DIAN,
	grdmis: DinozStatusId.GRDMIS,
	humiss: DinozStatusId.HUMISS,
	rasca: DinozStatusId.RASCAPHANDRE_DECOY,
	fcharm: DinozStatusId.FIRE_CHARM,
	wcharm: DinozStatusId.WATER_CHARM,
	palmes: DinozStatusId.FLIPPERS,
	astone: DinozStatusId.OLD_STONE,
	totem: DinozStatusId.ASHPOUK_TOTEM,
	tourna: DinozStatusId.TOURNA,
	vmem: DinozStatusId.VMEM,
	vkill: DinozStatusId.VENERABLE,
	fflag: DinozStatusId.FFLAG,
	ccard: DinozStatusId.MEMBERSHIP_CARD,
	shflag: DinozStatusId.SHFLAG,
	amulst: DinozStatusId.STRATEGY_IN_130_LESSONS,
	medal1: DinozStatusId.BRONZE_MEDAL_FORCEBRUT,
	medal2: DinozStatusId.SILVER_MEDAL_FORCEBRUT,
	medal3: DinozStatusId.GOLD_MEDAL_FORCEBRUT,
	medal4: DinozStatusId.DIAMOND_MEDAL_FORCEBRUT,
	gshop: DinozStatusId.FLOWERING_BRANCH,
	bckpck: DinozStatusId.BACKPACK,
	reinca: DinozStatusId.REINCARNATION,
	renais: DinozStatusId.RENAISSANCE,
	fspele: DinozStatusId.FSPELE,
	cup1: DinozStatusId.BRONZE_CUP,
	cup2: DinozStatusId.SILVER_CUP,
	cup3: DinozStatusId.GOLD_CUP,
	cup4: DinozStatusId.DIAMOND_CUP,
	sylkey: DinozStatusId.SYLVENOIRE_KEY,
	morsso: DinozStatusId.DARK_ORB,
	lvlup1: DinozStatusId.BROKEN_LIMIT_1,
	lvlup2: DinozStatusId.BROKEN_LIMIT_2,
	lvlup3: DinozStatusId.BROKEN_LIMIT_3,
	newski: DinozStatusId.ETHER_DROP,
	corail: DinozStatusId.CORAIL,
	ice: DinozStatusId.ICE_PIECE,
	potion: DinozStatusId.ANTI_SEDH_POTION,
	skull: DinozStatusId.SKULLY_MEMORY,
	plaza: DinozStatusId.DINOPLAZA,
	conts1: DinozStatusId.GOLD_MEDAL_BEAUTY,
	conts2: DinozStatusId.SILVER_MEDAL_BEAUTY,
	conts3: DinozStatusId.BRONZE_MEDAL_BEAUTY,
	maudit: DinozStatusId.CURSED,
	demon: DinozStatusId.DEMON,
	monisl: DinozStatusId.MONISL,
	cuzmal: DinozStatusId.CUSCOUZ_MALEDICTION,
	mcapt: DinozStatusId.CATCHING_GLOVE,
	joze: DinozStatusId.JOVEBOZE,
	sphere: DinozStatusId.SPHERE,
	freturn: DinozStatusId.FRETURN,
	wswmps: DinozStatusId.WEIRD_SWAMP_SEEN,
	swmk: DinozStatusId.SWAMP_MONSTERS_KNOWN,
	swbuoy: DinozStatusId.SWAMP_BUOY,
	swlant: DinozStatusId.SWAMP_LANTERN
};

export const dinozStatusKeyById = Object.fromEntries(
	Object.entries(dinozStatusIdByKey).map(([key, id]) => [id, key])
) as Partial<Record<number, string>>;
