/**
 * This file contains code derived from or adapted from:
 * Eternaltwin DinoRPG
 * Upstream file: https://gitlab.com/eternaltwin/dinorpg/dinorpg/-/blob/3a73bbc6d751e4916cc5fd2e5f23bc2cfd42fc6d/core/src/models/dinoz/StatusList.mts
 *
 * Copyright in the original contributions remains with the respective
 * authors and contributors.
 *
 * Modified by DinoRPG Remastered contributors from 2026-02-09 through 2026-08-04.
 * See NOTICE.md and the Git history for provenance and modification details.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
export enum DinozStatusId {
	BUOY = 1,
	CLIMBING_GEAR = 2,
	LANTERN = 3,
	SHOVEL = 4,
	ENHANCED_SHOVEL = 5,
	BROKEN_SHOVEL = 6,
	BROKEN_ENHANCED_SHOVEL = 7,
	SWAMP_MUD = 8,
	PURE_WATER = 9,
	BASALT_SHARD = 10,
	ZORS_GLOVE = 11,
	ZENBRO = 12,
	NENUPHAR_LEAF = 13,
	CHUTES = 14,
	JVBZ = 15,
	QWOOD = 16,
	QWHY = 17,
	QTAME = 18,
	DIAN = 19,
	GRDMIS = 20,
	HUMISS = 21,
	RASCAPHANDRE_DECOY = 22,
	FIRE_CHARM = 23,
	WATER_CHARM = 24,
	FLIPPERS = 25,
	OLD_STONE = 26,
	ASHPOUK_TOTEM = 27,
	TOURNA = 28,
	VMEM = 29,
	VENERABLE = 30,
	FFLAG = 31,
	MEMBERSHIP_CARD = 32,
	SHFLAG = 33,
	STRATEGY_IN_130_LESSONS = 34,
	BRONZE_MEDAL_FORCEBRUT = 35,
	SILVER_MEDAL_FORCEBRUT = 36,
	GOLD_MEDAL_FORCEBRUT = 37,
	DIAMOND_MEDAL_FORCEBRUT = 38,
	FLOWERING_BRANCH = 39,
	BACKPACK = 40,
	REINCARNATION = 41,
	RENAISSANCE = 42,
	FSPELE = 43,
	BRONZE_CUP = 44,
	SILVER_CUP = 45,
	GOLD_CUP = 46,
	DIAMOND_CUP = 47,
	SYLVENOIRE_KEY = 48,
	DARK_ORB = 49,
	BROKEN_LIMIT_1 = 50,
	BROKEN_LIMIT_2 = 51,
	BROKEN_LIMIT_3 = 52,
	ETHER_DROP = 53,
	CORAIL = 54,
	ICE_PIECE = 55,
	ANTI_SEDH_POTION = 56,
	SKULLY_MEMORY = 57,
	DINOPLAZA = 58,
	GOLD_MEDAL_BEAUTY = 59,
	SILVER_MEDAL_BEAUTY = 60,
	BRONZE_MEDAL_BEAUTY = 61,
	CURSED = 62,
	DEMON = 63,
	MONISL = 64, //NOT IMPLEMENTED YET
	CUSCOUZ_MALEDICTION = 65,
	CATCHING_GLOVE = 66,
	JOVEBOZE = 67,
	SPHERE = 68,
	FRETURN = 69, //HACK TO RETALK WITH A NPC IF THERE IS CONDITION UNMET
	WEIRD_SWAMP_SEEN = 70,
	SWAMP_MONSTERS_KNOWN = 71,
	SWAMP_BUOY = 72,
	SWAMP_LANTERN = 73,
	MAGNETITE_RANGER_SEEN = 74
}
